name: full stack family app

on: 
  pull_request: 

jobs:
  ci-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: install backend dependencies
        run: |
          cd backend
          npm i

      - name: install frontend dependencies
        run: |
          cd frontend
          npm i 
    
