name : full stack CI
on:
    pull_request:
        branches: [ main ]
jobs:
    ci-test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4.0.0
                
          - name: intall the backend dependencies
            run : |
                cd backend 
                npm i 
                cd ..

          - name: intall the frontend dependencies
            run : |
                cd frontend 
                npm i 
                cd ..

          - name: Install PM2 globally
            run : npm i --global pm2

          - name: run backend
            run : 

          - name: test backend status
            run : |
                cd backend
                npm i
                pm2 start src/server.j