name: full stack family app

on: 
  pull_request: 

jobs:
  ci-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: install backend dependencies
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd backend
          pm2 start server.js

      - name: install frontend dependencies

        run: |
          cd frontend
          npm i
          cd .. 
      
